### ISSUE TITLE
Exception - Cannot access empty property !!!

### ISSUE THREAD

**Issue by kbsenthilkumar** [crond-jaist/cylms#1]
I am getting the error message below while trying to add example yaml provided with CyLMS to Moodle. Please help.

INFO: cylms.py: Convert training content file '/root/cylms/training_example.yml' to SCORM package.
* INFO: cnt2lms.py: Process training content file '/root/cylms/training_example.yml'.
* INFO: cnt2lms.py: Create SCORM package '/root/cylms/training_example.yml.zip'.
* INFO: cylms.py: Add converted SCORM package '/root/cylms/training_example.yml.zip' to LMS.
* INFO: lms_mgmt.py: Copy package '/root/cylms/training_example.yml.zip' to
	Target '/var/www/moodledata/repository/training_content/training_content1.zip'.
training_example.yml.zip                      100%   94KB  94.4KB/s   00:00    
CyTrONE Training
1
2
* ERROR: lms_mgmt.py: Error when adding activity for course id '2' section id '1'
  Error message: Default exception handler: Exception - Cannot access empty property Debug: 
Error code: generalexceptionmessage
* line 71 of /home/csg/moosh/Moosh/Command/Moodle26/Activity/ActivityAdd.php: Error thrown
* line 297 of /home/csg/moosh/moosh.php: call to Moosh\Command\Moodle26\Activity\ActivityAdd->execute()

!!! Exception - Cannot access empty property !!!

* ERROR: cylms.py: Failed to add converted SCORM package '/root/cylms/training_example.yml.zip' to LMS.

**Comment by crond-jaist** [comment]
Sorry for the late reply, we somehow missed your issue. Do you still have the problem mentioned above? I suspect it's a configuration problem, as there is perhaps no course with id '2' in your Moodle setup. Could you check this?

**Comment by kbsenthilkumar** [comment]
I have overcome the error by adding the line below in ActivityAdd.php in Moosh.

if($name!=""){
    $moduledata->$name = $value;
}

The line is added in the method execute() in the class ActivityAdd.

I don't know whether it is the correct way.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by crond-jaist** [comment]
I am glad to hear that the issue is solved, and it seems to have been related to Moosh. Thanks for sending us the solution, but we have not encountered this kind of issue, so I cannot confirm whether your solution is correct or not.
